// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v5"
	"gorm.io/gorm"
	"hexa/internal/adapters/handler"
	"hexa/internal/adapters/repository"
	"hexa/internal/core/service"
)

// Injectors from wire.go:

// Penampung rakitan untuk Product
func InitializeProductHandler(e *echo.Echo, db *gorm.DB) *handler.HttpProductHandler {
	gormRepositoryStruct := repository.NewGormRepository(db)
	productService := service.NewProductService(gormRepositoryStruct)
	httpProductHandler := handler.NewHttpProductHandlerReturn(e, productService)
	return httpProductHandler
}

// Penampung rakitan untuk Wallet
func InitializeWalletHandler(e *echo.Echo, db *gorm.DB) *handler.HttpWalletHandler {
	walletRepositoryStruct := repository.NewWalletRepository(db)
	walletService := service.NewWalletService(walletRepositoryStruct)
	httpWalletHandler := handler.NewHttpWalletHandlerReturn(e, walletService)
	return httpWalletHandler
}
